theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
author: vnetkc
title: Toolkit for Git
url: https://www.tk4git.com
logo: https://pbs.twimg.com/profile_banners/1307179475013185536/1600727340
image: https://pbs.twimg.com/profile_banners/1307179475013185536/1600727340
twitter:
  username: toolkit_for_git
  card: summary_large_image
social:
  name: Toolkit for Git
  links:
    - https://www.tk4git.com
    - https://twitter.com/toolkit_for_git
    - https://github.com/toolkit-for-git
