theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
author: V-Network Solutions
twitter:
  username: toolkit_for_git
  card: summary
social:
  name: Toolkit for Git
  links:
    - https://www.tk4git.com
    - https://twitter.com/toolkit_for_git
    - https://github.com/toolkit-for-git
